twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/bootstrap_5.html.twig']
    globals:
        app_name: '%app.name%'
        app_url: '%app.url%'

when@test:
    twig:
        strict_variables: true
