monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: deduplicated
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels: ["!mailer"]
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!mailer"]
        deduplicated:
            type:    deduplication
            handler: symfony_mailer
        symfony_mailer:
            type:       symfony_mailer
            from_email: 'nepasrepondre@hautsdefrance.fr'
            to_email:   'etudes-logs@hautsdefrance.fr'
            subject:    '[Fonds de tarte] %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
